spring:
  application:
    name: security-service
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database_name
    username: your_db_username
    password: your_db_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # ??? create-drop ??? ??????????, ?? ??????? ? production
    show-sql: true # ??? ???????
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect