version: "3.8"

services:
  course-service:
    image: tymurmustafaiev/course-service:latest  # Указан образ из Docker Hub
    container_name: course-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://course-db:5432/course_service_db
      - SPRING_DATASOURCE_USERNAME=course_user
      - SPRING_DATASOURCE_PASSWORD=course_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    depends_on:
      - course-db
    networks:
      - course-network

  course-db:
    image: postgres:15
    container_name: course-db
    environment:
      POSTGRES_DB: course_service_db
      POSTGRES_USER: course_user
      POSTGRES_PASSWORD: course_password
    ports:
      - "5432:5432"
    networks:
      - course-network

networks:
  course-network:
    driver: bridge
